---
title: "DS_2003_midterm"
author: "Matthew Spalthoff"
date: "2023-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)
```

```{r}
vgsales = read.csv("C:/Users/matth/OneDrive/Documents/UVA/Third Year/DS 2003/vgsales.csv")
vgsales$Year = as.numeric(vgsales$Year)

sum(is.na(vgsales$Year))

summary(vgsales)
str(vgsales)

table(vgsales$Platform)
nrow(table(vgsales$Platform))

table(vgsales$Genre)
```

```{r}
vgsales_year = subset(vgsales, Year <= 2016 & Year >= 2000)
vg_pub = data.frame(table(vgsales_year$Publisher))
nrow(table(vgsales$Publisher))
vg_pub = vg_pub[order(-vg_pub$Freq), ]
vg_pub = vg_pub[c(1:21),]
vg_pub = vg_pub[-17, ]

vgsales_pub = vgsales_year[vgsales_year$Publisher %in% vg_pub$Var1, ]

vg_pub_10 = vg_pub[c(1:10),]

vg_pub_5 = vg_pub[c(1:5),]

vgsales_pub_10 = vgsales_year[vgsales_year$Publisher %in% vg_pub_10$Var1, ]

vgsales_pub_5 = vgsales_year[vgsales_year$Publisher %in% vg_pub_5$Var1, ]


p1 = ggplot(vgsales_pub_10, aes(x = Year, y = Global_Sales, fill = Publisher)) + 
  #geom_line(aes(color = Publisher)) #+ 
  geom_smooth(aes(color = Publisher), se = F)  + 
  #geom_jitter(aes(color = Publisher), alpha = 0.2)
  scale_color_brewer(palette = "Spectral") + 
  theme_bw() + 
  labs(title = "Top 10 Publisher Global Sales over Time",
       subtitle = "From 2000 to 2016") + 
       xlab("Year") + 
       ylab("Global Sales (in Millions)")
p1

```

```{r}

p11 = ggplot(vgsales_pub_5, aes(x = Year, y = Global_Sales)) + 
  geom_point() +
  geom_smooth(aes(color = Publisher), se = F, method = "lm")
p11

#vgsales_pub_factor_year = vgsales_pub
#vgsales_pub_factor_year$Year = as.factor(vgsales_pub_factor_year$Year)

vgsales_pub_binned = vgsales_pub
vgsales_pub_binned = vgsales_pub_binned %>% mutate(year_bin_5 = ntile(Year, n = 5))
vgsales_pub_binned$year_bin_5 = as.factor(vgsales_pub_binned$year_bin_5)

p2 = ggplot(vgsales_pub_binned, aes(x = NA_Sales, y = Publisher, fill = year_bin_5)) + 
  geom_density_ridges(scale = 3, alpha = 0.4)
p2
```


